# Generated by Django 2.1.4 on 2019-01-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Book2',
        ),
    ]
