# Generated by Django 2.1.7 on 2019-03-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bady',
            new_name='body',
        ),
    ]
